# -*- coding: utf-8 -*-
"""financeiro - Prever acoes do mercado

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sBu4fnI3aCDZ6wa5bKczYsHIoiHhg09o
"""

# Importa as bibliotecas necessárias
import pandas as pd
from io import StringIO
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# String que contém os dados da tabela
dados_acoes_str = """
Data,Fechamento_Anterior,Volume,Noticia_Positiva,Preco_Fechamento
01/05,10.00,120,0,10.15
02/05,10.15,150,0,10.10
03/05,10.10,135,0,10.25
06/05,10.25,180,1,10.60
07/05,10.60,220,1,10.75
08/05,10.75,190,0,10.70
09/05,10.70,170,0,10.85
10/05,10.85,200,1,11.20
13/05,11.20,250,0,11.15
14/05,11.15,210,0,11.05
"""

# 1. Cria o DataFrame
df_acoes = pd.read_csv(StringIO(dados_acoes_str))

# Define Features (X) e Target (y)
X = df_acoes.drop(['Data', 'Preco_Fechamento'], axis=1)
y = df_acoes['Preco_Fechamento']

# 2. Treinamento
# Usamos todo o conjunto para treino
X_train = X
y_train = y

# Instancia e treina o modelo de Regressão Linear
model_linear = LinearRegression()
model_linear.fit(X_train, y_train)

# 3. Avaliação
y_pred = model_linear.predict(X_train)

# Avalia as métricas
mse = mean_squared_error(y_train, y_pred)
r2 = r2_score(y_train, y_pred)

print("Treinamento com Regressão Linear concluído.")
print("\n--- Resultados da Avaliação (Regressão Linear) ---")
print(f"Erro Quadrático Médio (MSE): {mse:.4f}")
print(f"R-Quadrado (R²): {r2:.4f}")

import pandas as pd
# Analisar a importância/peso das features
coeficientes = pd.Series(model_linear.coef_, index=X.columns)
intercepto = model_linear.intercept_

print("\n--- Coeficientes do Modelo de Regressão Linear ---")
print("Intercepto (Preço Base sem outros fatores):", f"{intercepto:.4f}")
print("--- Peso de Cada Feature ---")
print(coeficientes.sort_values(ascending=False))

import pandas as pd
import numpy as np

# Cria o DataFrame para o novo dia de negociação
dados_novos_str = """
Fechamento_Anterior,Volume,Noticia_Positiva
11.05,230,0
"""
df_novo_dia = pd.read_csv(StringIO(dados_novos_str))

# Faz a previsão do preço de fechamento para o dia 15/05
# O 'model_linear' treinado anteriormente será usado aqui
previsao_preco = model_linear.predict(df_novo_dia)

# Obtém os coeficientes para explicar a previsão
coeficientes = model_linear.coef_
intercepto = model_linear.intercept_

print("--- Previsão para o Dia 15/05 ---")
print(f"Preço de Fechamento Previsto: R$ {previsao_preco[0]:.2f}")

import pandas as pd
from io import StringIO
import numpy as np

# Dados de entrada (dia 15/05)
dados_novos_str = """
Fechamento_Anterior,Volume,Noticia_Positiva
11.05,230,0
"""
df_novo_dia = pd.read_csv(StringIO(dados_novos_str))

# Dados de Coeficientes (extraídos da sua análise anterior)
intercepto = -1.2304
coeficientes = np.array([1.182998, -0.003868, 0.353645]) # Ordem: Fechamento_Anterior, Volume, Noticia_Positiva

# Mapeia os coeficientes para as features
X_columns = ['Fechamento_Anterior', 'Volume', 'Noticia_Positiva']
pesos = dict(zip(X_columns, coeficientes))

# Dados de entrada para o cálculo
inputs = df_novo_dia.iloc[0].to_dict()

# Calcula a contribuição de cada feature: Contribuição = Peso * Valor_Feature
contribuicoes = {k: pesos[k] * v for k, v in inputs.items()}

print("\n--- Contribuição de cada Fator para a Previsão (R$ 10,95) ---")
print(f"**1. Intercepto (Base do Modelo):** R$ {intercepto:.4f}")

soma_contribuicoes = 0
for feature, contribuicao in contribuicoes.items():
    print(f"   Contribuição de {feature}: R$ {contribuicao:.4f}")
    soma_contribuicoes += contribuicao

# Cálculo final
calculo_final = intercepto + soma_contribuicoes
print("------------------------------------------")
print(f"**Soma das Contribuições:** R$ {soma_contribuicoes:.4f}")
print(f"**Preço Final Previsto (Intercepto + Soma):** R$ {calculo_final:.2f}")